name = "QUBO"
uuid = "ce8c2e91-a970-4681-856b-16178c24a30c"
authors = ["pedromxavier <pedroxavier@psr-inc.com>", "pedroripper <pedroripper@psr-inc.com>", "joaquimg <joaquim@psr-inc.com>", "AndradeTiago <tiago.andrade@psr-inc.com>", "bernalde <dbernaln@purdue.edu>"]
version = "0.3.2-dev"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
QUBODrivers = "a3f166f7-2cd3-47b6-9e1e-6fbfe0449eb0"
QUBOTools = "60eb5b62-0a39-4ddc-84c5-97d2adff9319"
ToQUBO = "9a412ddf-83fa-43b6-9748-7843c851aa65"

[compat]
JuMP             = "1"
MathOptInterface = "1"
QUBODrivers      = "0.3"
QUBOTools        = "0.9"
ToQUBO           = "0.1.8"
julia            = "1.9"
