name = "QUBO"
uuid = "ce8c2e91-a970-4681-856b-16178c24a30c"
authors = ["pedromxavier <pedroxavier@psr-inc.com>", "pedroripper <pedroripper@psr-inc.com>", "joaquimg <joaquim@psr-inc.com>", "AndradeTiago <tiago.andrade@psr-inc.com>", "bernalde <dbernalneira@usra.edu>"]
version = "0.1.0"

[deps]
Anneal    = "e4d9eb7f-b088-426e-aeb5-1c0dae3d8abb"
QUBOTools = "60eb5b62-0a39-4ddc-84c5-97d2adff9319"
ToQUBO    = "9a412ddf-83fa-43b6-9748-7843c851aa65"

[compat]
Anneal    = "0.6.2"
QUBOTools = "0.6.1"
ToQUBO    = "0.1.5"
julia     = "1.6"
