name = "QUBOTools"
uuid = "60eb5b62-0a39-4ddc-84c5-97d2adff9319"
authors = ["pedromxavier <pedroxavier@psr-inc.com>"]
version = "0.3.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSONSchema = "7d188eb4-7ad8-530c-ae41-71a32a6d4692"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
JSON = "0.21.3"
JSONSchema = "1.0"
julia = "1.6"
