name: Documentation
on:
  push:
    branches: [main]
    tags: '*'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v3
        with:
          version: '1.10'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(path=@__DIR__); Pkg.instantiate()'
      - name: Build docs
        if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
        run: julia --project=docs/ docs/make.jl --skip-deploy
      - name: Build and deploy
        if: github.event_name != 'pull_request' || github.actor != 'dependabot[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
        run: julia --project=docs/ docs/make.jl
  build-multidocs:
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v3
        with:
          version: '1.10'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.instantiate()'
      - name: Aggregate and deploy
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            julia --project=docs/ docs/multimake.jl --skip-deploy
          else
            julia --project=docs/ docs/multimake.jl
          fi
