name: MultiDocumentation
on:
  workflow_run:
    workflows: ["Documentation"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'
      - uses: julia-actions/julia-buildpkg@latest
        with: 
            project: "docs/"
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
        run: julia --project=docs/ docs/make.jl