name: MultiDocumentation
on:
  workflow_run:
    workflows: ["Documentation"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.instantiate()'
      - name: Aggregate and deploy
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          julia --project=docs/ docs/multimake.jl
