name: Label Pull Requests

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    uses: JuliaQUBO/.github/.github/workflows/pr-labeler.yml@7373363a26cd68189b1f35f1d3fd31d46787a760
    with:
      configuration_path: .github/labeler.yml
